arch: xboundformer
gpu: '0'
net_layer: 50
dataset: isic2018
exp_name: test
fold: null
lr_seg: 0.0001
n_epochs: 150
bt_size: 12
seg_loss: 1
aug: 1
patience: 500
filter: 0
im_num: 1
ex_num: 1
xbound: 1
point_w: 1.0
folder_name: Default_folder

image_size: 256

print_metrics: False
save_latest: False

pretrained_model_path: /gemini/pretrain/pvt_v2_b2.pth
log_file_path: /gemini/logs/
trained_model_path: /gemini/output/
dataset_path: /gemini/data-1/data_isic161718/isic2018/
result_path: /gemini/output/
gt_format: '{}.png'