arch: xboundformer
gpu: '0'
net_layer: 50
dataset: isic2017
exp_name: test
fold: null
lr_seg: 0.0001
n_epochs: 150
bt_size: 12
seg_loss: 1
aug: 1
patience: 500
filter: 0
im_num: 1
ex_num: 1
xbound: 1
point_w: 1.0
folder_name: Default_folder

image_size: 256

print_metrics: True
save_latest: True

pretrained_model_path: /autodl-fs/data/pretrained_model/pvt_v2_b2.pth
log_file_path: ./log
trained_model_path: /autodl-fs/data/xboundformer/trained_model/
dataset_path: /autodl-fs/data/data_isic161718/isic2017/
result_path: /autodl-fs/data/xboundformer/result/
gt_format: '{}_segmentation.png'